// <auto-generated />
using System;
using AccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110093728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Models.Achievement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AchievementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("achievement_type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("points");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_achievements_user_id");

                    b.HasIndex("UserId", "AchievementType")
                        .HasDatabaseName("idx_achievements_user_type");

                    b.ToTable("achievements", "users");
                });

            modelBuilder.Entity("AccountService.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique()
                        .HasDatabaseName("idx_permissions_resource_action");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = "read",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View user profiles",
                            Name = "view_profile",
                            Resource = "user"
                        },
                        new
                        {
                            Id = 2L,
                            Action = "update",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit own profile",
                            Name = "edit_own_profile",
                            Resource = "user"
                        },
                        new
                        {
                            Id = 3L,
                            Action = "delete",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete own account",
                            Name = "delete_own_account",
                            Resource = "user"
                        },
                        new
                        {
                            Id = 4L,
                            Action = "read",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View problems",
                            Name = "view_problems",
                            Resource = "problem"
                        },
                        new
                        {
                            Id = 5L,
                            Action = "create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Submit problem solutions",
                            Name = "submit_solution",
                            Resource = "submission"
                        },
                        new
                        {
                            Id = 6L,
                            Action = "create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create new problems",
                            Name = "create_problem",
                            Resource = "problem"
                        },
                        new
                        {
                            Id = 7L,
                            Action = "update",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit problems",
                            Name = "edit_problem",
                            Resource = "problem"
                        },
                        new
                        {
                            Id = 8L,
                            Action = "delete",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete problems",
                            Name = "delete_problem",
                            Resource = "problem"
                        },
                        new
                        {
                            Id = 9L,
                            Action = "read",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View contests",
                            Name = "view_contests",
                            Resource = "contest"
                        },
                        new
                        {
                            Id = 10L,
                            Action = "create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Participate in contests",
                            Name = "participate_contest",
                            Resource = "contest_participation"
                        },
                        new
                        {
                            Id = 11L,
                            Action = "create",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create contests",
                            Name = "create_contest",
                            Resource = "contest"
                        },
                        new
                        {
                            Id = 12L,
                            Action = "update",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit contests",
                            Name = "edit_contest",
                            Resource = "contest"
                        },
                        new
                        {
                            Id = 13L,
                            Action = "delete",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete contests",
                            Name = "delete_contest",
                            Resource = "contest"
                        },
                        new
                        {
                            Id = 14L,
                            Action = "manage",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage user accounts",
                            Name = "manage_users",
                            Resource = "user_management"
                        },
                        new
                        {
                            Id = 15L,
                            Action = "manage",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage roles and permissions",
                            Name = "manage_roles",
                            Resource = "role_management"
                        },
                        new
                        {
                            Id = 16L,
                            Action = "read",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View system analytics",
                            Name = "view_analytics",
                            Resource = "analytics"
                        },
                        new
                        {
                            Id = 17L,
                            Action = "manage",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moderate user content",
                            Name = "moderate_content",
                            Resource = "content_moderation"
                        },
                        new
                        {
                            Id = 18L,
                            Action = "manage",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ban/unban users",
                            Name = "ban_users",
                            Resource = "user_ban"
                        });
                });

            modelBuilder.Entity("AccountService.Models.RatingHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<long?>("ContestId")
                        .HasColumnType("bigint")
                        .HasColumnName("contest_id");

                    b.Property<int>("NewRating")
                        .HasColumnType("integer")
                        .HasColumnName("new_rating");

                    b.Property<int>("OldRating")
                        .HasColumnType("integer")
                        .HasColumnName("old_rating");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestId")
                        .HasDatabaseName("idx_rating_history_contest");

                    b.HasIndex("UserId", "ChangedAt")
                        .HasDatabaseName("idx_rating_history_user_changed");

                    b.ToTable("rating_history", "users");
                });

            modelBuilder.Entity("AccountService.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("replaced_by_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("idx_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "users");
                });

            modelBuilder.Entity("AccountService.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_roles_name");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regular user with basic permissions",
                            IsSystemRole = true,
                            Name = "user"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Problem setter who can create problems",
                            IsSystemRole = true,
                            Name = "setter"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moderator with content moderation permissions",
                            IsSystemRole = true,
                            Name = "moderator"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator with full system access",
                            IsSystemRole = true,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Super administrator with unrestricted access",
                            IsSystemRole = true,
                            Name = "super_admin"
                        });
                });

            modelBuilder.Entity("AccountService.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("idx_role_permissions_permission");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("idx_role_permissions_role_permission");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1060),
                            PermissionId = 1L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 2L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 3L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 4L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 5L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 9L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(1200),
                            PermissionId = 10L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2140),
                            PermissionId = 1L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2200),
                            PermissionId = 2L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2240),
                            PermissionId = 3L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 4L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 5L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 6L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 7L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 9L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2250),
                            PermissionId = 10L,
                            RoleId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2630),
                            PermissionId = 1L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2630),
                            PermissionId = 2L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 3L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 4L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 5L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 6L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 7L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 8L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 9L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 10L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 11L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 12L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2640),
                            PermissionId = 17L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2650),
                            PermissionId = 18L,
                            RoleId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 1L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 2L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 3L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 4L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 5L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 6L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 7L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 8L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 9L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 10L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 11L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 12L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2980),
                            PermissionId = 13L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 14L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 15L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 16L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 17L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 18L,
                            RoleId = 4L
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 1L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 2L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 51L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 3L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 52L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 4L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 53L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 5L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 54L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 6L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 55L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 7L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 56L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 8L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 57L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(2990),
                            PermissionId = 9L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 58L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 10L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 59L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 11L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 60L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 12L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 61L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 13L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 62L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 14L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 63L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 15L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 64L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 16L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 65L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 17L,
                            RoleId = 5L
                        },
                        new
                        {
                            Id = 66L,
                            CreatedAt = new DateTime(2025, 11, 10, 9, 37, 28, 421, DateTimeKind.Utc).AddTicks(3000),
                            PermissionId = 18L,
                            RoleId = 5L
                        });
                });

            modelBuilder.Entity("AccountService.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1500)
                        .HasColumnName("rating");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("verification_token");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_token_expiry");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("idx_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("idx_users_normalized_username");

                    b.HasIndex("Rating")
                        .HasDatabaseName("idx_users_rating");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("AccountService.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_user_roles_role");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_roles_user_role");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("AccountService.Models.UserSettings", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<bool>("ContestReminders")
                        .HasColumnType("boolean")
                        .HasColumnName("contest_reminders");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean")
                        .HasColumnName("email_notifications");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_preference");

                    b.Property<bool>("ShowRating")
                        .HasColumnType("boolean")
                        .HasColumnName("show_rating");

                    b.Property<string>("SolutionVisibility")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("solution_visibility");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("theme");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_settings", "users");
                });

            modelBuilder.Entity("AccountService.Models.UserStatistics", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal>("AcceptanceRate")
                        .HasColumnType("numeric")
                        .HasColumnName("acceptance_rate");

                    b.Property<int>("AcceptedSubmissions")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_submissions");

                    b.Property<int>("ContestsParticipated")
                        .HasColumnType("integer")
                        .HasColumnName("contests_participated");

                    b.Property<int?>("CountryRank")
                        .HasColumnType("integer")
                        .HasColumnName("country_rank");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<int>("EasySolved")
                        .HasColumnType("integer")
                        .HasColumnName("easy_solved");

                    b.Property<int?>("GlobalRank")
                        .HasColumnType("integer")
                        .HasColumnName("global_rank");

                    b.Property<int>("HardSolved")
                        .HasColumnType("integer")
                        .HasColumnName("hard_solved");

                    b.Property<DateTime?>("LastSubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_submission_date");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer")
                        .HasColumnName("max_streak");

                    b.Property<int>("MediumSolved")
                        .HasColumnType("integer")
                        .HasColumnName("medium_solved");

                    b.Property<int>("ProblemsSolved")
                        .HasColumnType("integer")
                        .HasColumnName("problems_solved");

                    b.Property<int>("TotalSubmissions")
                        .HasColumnType("integer")
                        .HasColumnName("total_submissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.HasIndex("GlobalRank")
                        .HasDatabaseName("idx_user_statistics_global_rank");

                    b.ToTable("user_statistics", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", "users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", "users");
                });

            modelBuilder.Entity("AccountService.Models.Achievement", b =>
                {
                    b.HasOne("AccountService.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Models.RatingHistory", b =>
                {
                    b.HasOne("AccountService.Models.User", "User")
                        .WithMany("RatingHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Models.RefreshToken", b =>
                {
                    b.HasOne("AccountService.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Models.RolePermission", b =>
                {
                    b.HasOne("AccountService.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountService.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccountService.Models.UserRole", b =>
                {
                    b.HasOne("AccountService.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedBy");

                    b.HasOne("AccountService.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountService.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Models.UserSettings", b =>
                {
                    b.HasOne("AccountService.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("AccountService.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountService.Models.UserStatistics", b =>
                {
                    b.HasOne("AccountService.Models.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("AccountService.Models.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("AccountService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("AccountService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccountService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("AccountService.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccountService.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AccountService.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AccountService.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("RatingHistory");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");

                    b.Navigation("Statistics");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
